# Generated by Django 4.1 on 2022-12-06 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_participante'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participante',
            name='festival',
        ),
        migrations.RemoveField(
            model_name='participante',
            name='user',
        ),
        migrations.DeleteModel(
            name='Festival',
        ),
        migrations.DeleteModel(
            name='Participante',
        ),
        migrations.DeleteModel(
            name='Rua',
        ),
    ]
